# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set version env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore IdoitSharp/IdoitSharp.csproj
    - name: Build x64
      run: dotnet publish IdoitSharp/IdoitSharp.csproj -p:PublishProfile=Release --no-restore
    - name: Release files
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        files: |
            IdoitSharp/bin/publish/IdoitSharp.${{ env.RELEASE_VERSION }}.nupkg
    - name: upload nuget
      run: dotnet nuget push IdoitSharp/bin/publish/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
